### PR TITLE
Documentation: translate setup.sh and PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by might4**
# Explanation

I just translated Setup.sh and PULL_REQUEST_TEMPLATE.md
**Related Issues:** #72 #74 
## Category of Thing You Changed:

- [ ] Bug Fix
- [ ] Feature
- [x] Documentation

### CODE REVIEW

**Review by cagrimertbakirci — CHANGES_REQUESTED** [review]
# Explanation



**Related Issue:** #

## Change Category:

- [ ] Bug Fix
- [ ] Feature
- [ ] Documentation

## Aditional Information:



# How to Test?



# Checklist:

- [ ] My code complies with this project's code formatting guidelines.
- [ ] I reviewed my code.
- [ ] I added comments especially in portions that may be difficult to understand.
- [ ] If necessary, I updated the documentation.
- [ ] Changes I made do not produce new issues.
- [ ] I added or updated tests based on my changes.
- [ ] If any, all changes related to my changes are already present in the main branch.

**Comment by cagrimertbakirci** [comment]
Great job, thanks! 

I wanted to make minor changes to the code, but the "comment" portions of my review seems to have been left out in the above comment. Please compare only the titles and checklists for my corrections and resend.

**Comment by might4** [comment]
@cagrimertbakirci, before closing this PR, state your corrections about the comment portions if you want to so I can correct them as well.

**Comment by cagrimertbakirci** [comment]
Oh no, there were no corrections in the comment portions. It just didn't bring them in here (which were left as is anyway). So it's ready to go. :)

**Review by cagrimertbakirci — APPROVED** [review]

**Pull request merged**
